[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production.variables]
NODE_ENV = "production"
PORT = "$PORT"

[environments.production.plugins.mongodb]
source = "mongodb"

[environments.production.plugins.redis]
source = "redis"